name: chirpy_shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
upload_to: none
# repository: https://github.com/my_org/my_repo
environment:
  sdk: "^3.3.0"

# Add regular dependencies here.
dependencies:
  chirpy_client:
    path: ../chirpy_client
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
