name: chirpy_client
description: Starting point for a Serverpod client.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  chirpy_shared:
    path: ../chirpy_shared
  serverpod_auth_client: 2.0.0-alpha.2
  serverpod_client: 2.0.0-alpha.2
