type: server

client_package_path: ../chirpy_client

modules:
  serverpod_auth:
    nickname: auth

extraClasses:
  - package:chirpy_shared/chirpy_shared.dart:Filter
  - package:chirpy_shared/chirpy_shared.dart:PostFilter
