name: chirpy_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  serverpod_auth_server: 1.2.5
  serverpod: 1.2.5

dev_dependencies:
  lints: ^3.0.0
